name: Sample with Microsoft SBOM Generation

on:
    push:
      branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Generate Python SBOM
      uses: CycloneDX/gh-python-generate-sbom@v2
      with:
        input: ./requirements.txt
        output: ./bom.csv  # Change the output file extension to .csv
        format: table      # Specify the format as "table" for tabular output


    

