name: Generate SBOM and Upload Artifact

on:
  push:
    branches: [master]

jobs:
  generate-sbom:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  

    - name: Install Microsoft SBOM Tool
      run: |
        pip install MicrosoftSBOMTool  

    - name: Generate SBOM
      run: |
        sbom generate --output sbom.xml  

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: sbom  # Name of the artifact
        path: sbom.xml  # Path to the generated SBOM file
