name: Generate SBOM and Upload Artifact

on:
  push:
    branches: [master]

jobs:
  generate-sbom:

    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y curl

    - name: Install Microsoft SBOM Tool
      run: |
        curl -sSL https://example.com/sbom-tool-install-script.sh | bash  

    - name: Generate SBOM
      run: |
        sbom-tool generate --output sbom.xml  

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: sbom  # Name of the artifact
        path: sbom.xml  # Path to the generated SBOM file
