name: SPDX

on:
  push:
    branches: [master]

jobs:
  generate-sbom:

    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.13'
      - name: Create spdx-file
        id: spdx-builder
        uses: philips-software/spdx-action@v0.9.1.1
        with:
          project: my-project
          mode: ort
      with:
        input: ./requirements.txt
        output: ./bom.json
        format: json
