name: severity

on:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: 0.0.1.release
          username: KarthikShetty5
          password: ${{ secrets.DOCKER }}
      -
        name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: localbuild/testimage:latest
          severity_threshold: HIGH
