name: build
on: 
  push:
  issue_comment:
    types: [created, edited]

jobs:
  scan:
    if: contains(github.event.comment.body, '/scan')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: 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
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Running tern action for default output.`
            })
      - uses: philips-labs/tern-action@v1.1.0
        id: scan
        with:
          image: localbuild/testimage:latest
          format: json
      - uses: actions/upload-artifact@v2
        with:
          name: tern
          path: ${{ steps.scan.outputs.file}}